<a href="https://colab.research.google.com/github/Pavan-Gandham/ML-and-Deep-Learning/blob/main/DeepLearningUSAHousingPricePrediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import datetime
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import  Dense

In [ ]:
data = pd.read_csv("/content/USA_Housing.csv")

In [ ]:
data.head()

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Price,Unnamed: 5,Unnamed: 6
0,79545.45857,5.682861,7.009188,4.09,1.059034e+06,NaN,NaN
1,79248.64245,6.002900,6.730821,3.09,1.505891e+06,NaN,NaN
2,61287.06718,5.865890,8.512727,5.13,1.058988e+06,NaN,NaN
3,63345.24005,7.188236,5.586729,3.26,1.260617e+06,NaN,NaN
4,59982.19723,5.040555,7.839388,4.23,6.309435e+05,NaN,NaN

In [ ]:
df = pd.DataFrame(data)

In [ ]:
for col in df.columns:
    if 'Unnamed' in col:
        del df[col]

In [ ]:
df.head()

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Price,Unnamed: 5,Unnamed: 6
0,79545.45857,5.682861,7.009188,4.09,1.059034e+06,NaN,NaN
1,79248.64245,6.002900,6.730821,3.09,1.505891e+06,NaN,NaN
2,61287.06718,5.865890,8.512727,5.13,1.058988e+06,NaN,NaN
3,63345.24005,7.188236,5.586729,3.26,1.260617e+06,NaN,NaN
4,59982.19723,5.040555,7.839388,4.23,6.309435e+05,NaN,NaN

In [ ]:
for col in df.columns:
    if 'Unnamed' in col:
        del df[col]

In [ ]:
data.head()

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Price,Unnamed: 5,Unnamed: 6
0,79545.45857,5.682861,7.009188,4.09,1.059034e+06,NaN,NaN
1,79248.64245,6.002900,6.730821,3.09,1.505891e+06,NaN,NaN
2,61287.06718,5.865890,8.512727,5.13,1.058988e+06,NaN,NaN
3,63345.24005,7.188236,5.586729,3.26,1.260617e+06,NaN,NaN
4,59982.19723,5.040555,7.839388,4.23,6.309435e+05,NaN,NaN

In [ ]:
# x=dataset[:,0:5]
# print(x.shape)
# y=dataset[:,-1]
# y=np.reshape(y, (-1,1))
# print(y.shape)
X= df.values[:,0:3]
Y=  df.values[:,4]
Y=np.reshape(Y, (-1,1))
print(X.shape)
print(Y.shape)

(5000, 3)
(5000, 1)

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(X,Y)
# 75% 25%
# print(y_test.shape)

In [ ]:
model=Sequential()
model.add(Dense(12,input_dim=3,activation='relu')) #check the input dimension(number of inputs) is important
model.add(Dense(8,activation='relu'))
model.add(Dense(1,activation='linear'))
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_3 (Dense)              (None, 12)                48
_________________________________________________________________
dense_4 (Dense)              (None, 8)                 104
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 9
=================================================================
Total params: 161
Trainable params: 161
Non-trainable params: 0
_________________________________________________________________

In [ ]:
model.compile(loss='mse',optimizer='adam',metrics=['mse','mae'])

In [ ]:
history= model.fit(x_train,y_train,epochs=150,batch_size=20)

Epoch 1/150
188/188 [==============================] - 1s 2ms/step - loss: 1594553794560.0000 - mse: 1594553794560.0000 - mae: 1212553.7500
Epoch 2/150
188/188 [==============================] - 1s 3ms/step - loss: 1341522051072.0000 - mse: 1341522051072.0000 - mae: 1105807.1250
Epoch 3/150
188/188 [==============================] - 1s 3ms/step - loss: 793212223488.0000 - mse: 793212223488.0000 - mae: 826485.0000
Epoch 4/150
188/188 [==============================] - 0s 2ms/step - loss: 252491005952.0000 - mse: 252491005952.0000 - mae: 422063.5000
Epoch 5/150
188/188 [==============================] - 1s 3ms/step - loss: 87040958464.0000 - mse: 87040958464.0000 - mae: 236923.3125
Epoch 6/150
188/188 [==============================] - 0s 2ms/step - loss: 75641733120.0000 - mse: 75641733120.0000 - mae: 220879.2188
Epoch 7/150
188/188 [==============================] - 0s 2ms/step - loss: 75500494848.0000 - mse: 75500486656.0000 - mae: 220543.7500
Epoch 8/150
188/188 [==============================] - 0s 2ms/step - loss: 75518255104.0000 - mse: 75518255104.0000 - mae: 220574.1719
Epoch 9/150
188/188 [==============================] - 0s 3ms/step - loss: 75499028480.0000 - mse: 75499028480.0000 - mae: 220459.7031
Epoch 10/150
188/188 [==============================] - 0s 2ms/step - loss: 75544936448.0000 - mse: 75544936448.0000 - mae: 220556.7812
Epoch 11/150
188/188 [==============================] - 0s 3ms/step - loss: 75530330112.0000 - mse: 75530330112.0000 - mae: 220548.0625
Epoch 12/150
188/188 [==============================] - 0s 2ms/step - loss: 75528462336.0000 - mse: 75528462336.0000 - mae: 220573.8281
Epoch 13/150
188/188 [==============================] - 0s 2ms/step - loss: 75546017792.0000 - mse: 75546017792.0000 - mae: 220609.7969
Epoch 14/150
188/188 [==============================] - 0s 3ms/step - loss: 75547451392.0000 - mse: 75547451392.0000 - mae: 220652.5938
Epoch 15/150
188/188 [==============================] - 0s 2ms/step - loss: 75598659584.0000 - mse: 75598659584.0000 - mae: 220726.3750
Epoch 16/150
188/188 [==============================] - 0s 2ms/step - loss: 75518541824.0000 - mse: 75518541824.0000 - mae: 220602.0781
Epoch 17/150
188/188 [==============================] - 1s 4ms/step - loss: 75595243520.0000 - mse: 75595243520.0000 - mae: 220628.0781
Epoch 18/150
188/188 [==============================] - 1s 4ms/step - loss: 75564908544.0000 - mse: 75564908544.0000 - mae: 220580.3125
Epoch 19/150
188/188 [==============================] - 1s 3ms/step - loss: 75544854528.0000 - mse: 75544854528.0000 - mae: 220576.2188
Epoch 20/150
188/188 [==============================] - 1s 3ms/step - loss: 75551457280.0000 - mse: 75551457280.0000 - mae: 220643.1250
Epoch 21/150
188/188 [==============================] - 1s 4ms/step - loss: 75487232000.0000 - mse: 75487248384.0000 - mae: 220706.4375
Epoch 22/150
188/188 [==============================] - 1s 4ms/step - loss: 75626979328.0000 - mse: 75626979328.0000 - mae: 221082.4688
Epoch 23/150
188/188 [==============================] - 1s 3ms/step - loss: 75592884224.0000 - mse: 75592884224.0000 - mae: 220582.1094
Epoch 24/150
188/188 [==============================] - 1s 3ms/step - loss: 75561115648.0000 - mse: 75561115648.0000 - mae: 220721.5625
Epoch 25/150
188/188 [==============================] - 1s 4ms/step - loss: 75592335360.0000 - mse: 75592335360.0000 - mae: 220689.9688
Epoch 26/150
188/188 [==============================] - 1s 3ms/step - loss: 75558289408.0000 - mse: 75558289408.0000 - mae: 220710.9531
Epoch 27/150
188/188 [==============================] - 0s 2ms/step - loss: 75599028224.0000 - mse: 75599028224.0000 - mae: 220598.1719
Epoch 28/150
188/188 [==============================] - 1s 3ms/step - loss: 75524538368.0000 - mse: 75524538368.0000 - mae: 220494.8281
Epoch 29/150
188/188 [==============================] - 0s 2ms/step - loss: 75546058752.0000 - mse: 75546058752.0000 - mae: 220574.7812
Epoch 30/150
188/188 [==============================] - 1s 3ms/step - loss: 75605139456.0000 - mse: 75605139456.0000 - mae: 220641.3281
Epoch 31/150
188/188 [==============================] - 0s 2ms/step - loss: 75542978560.0000 - mse: 75542978560.0000 - mae: 220540.7031
Epoch 32/150
188/188 [==============================] - 0s 3ms/step - loss: 75480965120.0000 - mse: 75480965120.0000 - mae: 220503.5000
Epoch 33/150
188/188 [==============================] - 0s 3ms/step - loss: 75627814912.0000 - mse: 75627806720.0000 - mae: 220679.1875
Epoch 34/150
188/188 [==============================] - 0s 2ms/step - loss: 75500216320.0000 - mse: 75500216320.0000 - mae: 220538.3125
Epoch 35/150
188/188 [==============================] - 0s 3ms/step - loss: 75556003840.0000 - mse: 75556003840.0000 - mae: 220646.2969
Epoch 36/150
188/188 [==============================] - 0s 2ms/step - loss: 75675992064.0000 - mse: 75675992064.0000 - mae: 220819.1719
Epoch 37/150
188/188 [==============================] - 0s 2ms/step - loss: 75385880576.0000 - mse: 75385880576.0000 - mae: 220296.3594
Epoch 38/150
188/188 [==============================] - 0s 2ms/step - loss: 75607236608.0000 - mse: 75607236608.0000 - mae: 220839.6406
Epoch 39/150
188/188 [==============================] - 0s 2ms/step - loss: 75627560960.0000 - mse: 75627560960.0000 - mae: 220781.7344
Epoch 40/150
188/188 [==============================] - 0s 2ms/step - loss: 75512668160.0000 - mse: 75512668160.0000 - mae: 220560.6719
Epoch 41/150
188/188 [==============================] - 0s 3ms/step - loss: 75606466560.0000 - mse: 75606466560.0000 - mae: 220581.8750
Epoch 42/150
188/188 [==============================] - 0s 2ms/step - loss: 75573313536.0000 - mse: 75573313536.0000 - mae: 220705.7656
Epoch 43/150
188/188 [==============================] - 0s 2ms/step - loss: 75598675968.0000 - mse: 75598675968.0000 - mae: 220737.7031
Epoch 44/150
188/188 [==============================] - 0s 2ms/step - loss: 75535335424.0000 - mse: 75535327232.0000 - mae: 220595.1719
Epoch 45/150
188/188 [==============================] - 0s 2ms/step - loss: 75575255040.0000 - mse: 75575263232.0000 - mae: 220697.2969
Epoch 46/150
188/188 [==============================] - 0s 2ms/step - loss: 75544535040.0000 - mse: 75544535040.0000 - mae: 220571.4219
Epoch 47/150
188/188 [==============================] - 1s 3ms/step - loss: 75583602688.0000 - mse: 75583602688.0000 - mae: 220553.7656
Epoch 48/150
188/188 [==============================] - 1s 4ms/step - loss: 75550253056.0000 - mse: 75550253056.0000 - mae: 220596.2656
Epoch 49/150
188/188 [==============================] - 1s 4ms/step - loss: 75524489216.0000 - mse: 75524497408.0000 - mae: 220576.3750
Epoch 50/150
188/188 [==============================] - 1s 4ms/step - loss: 75574345728.0000 - mse: 75574345728.0000 - mae: 220692.3125
Epoch 51/150
188/188 [==============================] - 1s 3ms/step - loss: 75555594240.0000 - mse: 75555594240.0000 - mae: 220654.1250
Epoch 52/150
188/188 [==============================] - 1s 4ms/step - loss: 75591458816.0000 - mse: 75591458816.0000 - mae: 220500.2656
Epoch 53/150
188/188 [==============================] - 1s 4ms/step - loss: 75519598592.0000 - mse: 75519598592.0000 - mae: 220582.6250
Epoch 54/150
188/188 [==============================] - 1s 3ms/step - loss: 75610300416.0000 - mse: 75610300416.0000 - mae: 220610.4062
Epoch 55/150
188/188 [==============================] - 0s 2ms/step - loss: 75613421568.0000 - mse: 75613421568.0000 - mae: 220771.3438
Epoch 56/150
188/188 [==============================] - 0s 2ms/step - loss: 75503796224.0000 - mse: 75503796224.0000 - mae: 220694.9062
Epoch 57/150
188/188 [==============================] - 0s 3ms/step - loss: 75535114240.0000 - mse: 75535114240.0000 - mae: 220758.5938
Epoch 58/150
188/188 [==============================] - 0s 2ms/step - loss: 75575001088.0000 - mse: 75575001088.0000 - mae: 220737.5469
Epoch 59/150
188/188 [==============================] - 0s 2ms/step - loss: 75513724928.0000 - mse: 75513724928.0000 - mae: 220626.0938
Epoch 60/150
188/188 [==============================] - 0s 2ms/step - loss: 75482374144.0000 - mse: 75482374144.0000 - mae: 220528.4219
Epoch 61/150
188/188 [==============================] - 0s 2ms/step - loss: 75590803456.0000 - mse: 75590803456.0000 - mae: 220694.6406
Epoch 62/150
188/188 [==============================] - 0s 2ms/step - loss: 75549843456.0000 - mse: 75549843456.0000 - mae: 220633.6875
Epoch 63/150
188/188 [==============================] - 0s 2ms/step - loss: 75574837248.0000 - mse: 75574837248.0000 - mae: 220663.6719
Epoch 64/150
188/188 [==============================] - 0s 2ms/step - loss: 75547533312.0000 - mse: 75547533312.0000 - mae: 220645.1562
Epoch 65/150
188/188 [==============================] - 0s 2ms/step - loss: 75518484480.0000 - mse: 75518484480.0000 - mae: 220683.1094
Epoch 66/150
188/188 [==============================] - 0s 2ms/step - loss: 75508916224.0000 - mse: 75508916224.0000 - mae: 220494.9844
Epoch 67/150
188/188 [==============================] - 0s 2ms/step - loss: 75579236352.0000 - mse: 75579236352.0000 - mae: 220635.3281
Epoch 68/150
188/188 [==============================] - 0s 3ms/step - loss: 75531919360.0000 - mse: 75531919360.0000 - mae: 220641.2969
Epoch 69/150
188/188 [==============================] - 0s 2ms/step - loss: 75584102400.0000 - mse: 75584102400.0000 - mae: 220637.9219
Epoch 70/150
188/188 [==============================] - 0s 2ms/step - loss: 75570954240.0000 - mse: 75570954240.0000 - mae: 220709.7188
Epoch 71/150
188/188 [==============================] - 0s 2ms/step - loss: 75591401472.0000 - mse: 75591401472.0000 - mae: 220655.8906
Epoch 72/150
188/188 [==============================] - 0s 2ms/step - loss: 75597438976.0000 - mse: 75597438976.0000 - mae: 220744.1250
Epoch 73/150
188/188 [==============================] - 1s 3ms/step - loss: 75544788992.0000 - mse: 75544788992.0000 - mae: 220573.4844
Epoch 74/150
188/188 [==============================] - 0s 2ms/step - loss: 75585028096.0000 - mse: 75585028096.0000 - mae: 220613.1094
Epoch 75/150
188/188 [==============================] - 0s 3ms/step - loss: 75548418048.0000 - mse: 75548418048.0000 - mae: 220599.7969
Epoch 76/150
188/188 [==============================] - 1s 3ms/step - loss: 75565703168.0000 - mse: 75565703168.0000 - mae: 220642.6094
Epoch 77/150
188/188 [==============================] - 1s 4ms/step - loss: 75587264512.0000 - mse: 75587264512.0000 - mae: 220595.2812
Epoch 78/150
188/188 [==============================] - 1s 4ms/step - loss: 75468627968.0000 - mse: 75468627968.0000 - mae: 220449.4531
Epoch 79/150
188/188 [==============================] - 1s 4ms/step - loss: 75598430208.0000 - mse: 75598430208.0000 - mae: 220702.3906
Epoch 80/150
188/188 [==============================] - 1s 4ms/step - loss: 75557781504.0000 - mse: 75557781504.0000 - mae: 220682.9844
Epoch 81/150
188/188 [==============================] - 1s 4ms/step - loss: 75522080768.0000 - mse: 75522080768.0000 - mae: 220582.4531
Epoch 82/150
188/188 [==============================] - 1s 4ms/step - loss: 75567284224.0000 - mse: 75567284224.0000 - mae: 220583.7812
Epoch 83/150
188/188 [==============================] - 1s 3ms/step - loss: 75558707200.0000 - mse: 75558707200.0000 - mae: 220623.7344
Epoch 84/150
188/188 [==============================] - 1s 3ms/step - loss: 75584397312.0000 - mse: 75584397312.0000 - mae: 220748.6875
Epoch 85/150
188/188 [==============================] - 0s 3ms/step - loss: 75659755520.0000 - mse: 75659755520.0000 - mae: 220803.1719
Epoch 86/150
188/188 [==============================] - 0s 3ms/step - loss: 75565424640.0000 - mse: 75565424640.0000 - mae: 220654.4531
Epoch 87/150
188/188 [==============================] - 1s 3ms/step - loss: 75571830784.0000 - mse: 75571830784.0000 - mae: 220630.9844
Epoch 88/150
188/188 [==============================] - 0s 3ms/step - loss: 75551391744.0000 - mse: 75551391744.0000 - mae: 220498.2031
Epoch 89/150
188/188 [==============================] - 0s 3ms/step - loss: 75507417088.0000 - mse: 75507417088.0000 - mae: 220640.7500
Epoch 90/150
188/188 [==============================] - 0s 2ms/step - loss: 75477876736.0000 - mse: 75477876736.0000 - mae: 220615.5469
Epoch 91/150
188/188 [==============================] - 0s 3ms/step - loss: 75611922432.0000 - mse: 75611930624.0000 - mae: 220696.6562
Epoch 92/150
188/188 [==============================] - 0s 2ms/step - loss: 75614691328.0000 - mse: 75614691328.0000 - mae: 220733.4844
Epoch 93/150
188/188 [==============================] - 0s 2ms/step - loss: 75527593984.0000 - mse: 75527593984.0000 - mae: 220582.8438
Epoch 94/150
188/188 [==============================] - 0s 2ms/step - loss: 75583291392.0000 - mse: 75583291392.0000 - mae: 220698.3750
Epoch 95/150
188/188 [==============================] - 0s 2ms/step - loss: 75552972800.0000 - mse: 75552972800.0000 - mae: 220643.6562
Epoch 96/150
188/188 [==============================] - 0s 2ms/step - loss: 75523719168.0000 - mse: 75523719168.0000 - mae: 220597.1562
Epoch 97/150
188/188 [==============================] - 0s 2ms/step - loss: 75618058240.0000 - mse: 75618058240.0000 - mae: 220724.5000
Epoch 98/150
188/188 [==============================] - 0s 3ms/step - loss: 75571281920.0000 - mse: 75571281920.0000 - mae: 220597.7812
Epoch 99/150
188/188 [==============================] - 0s 2ms/step - loss: 75614650368.0000 - mse: 75614650368.0000 - mae: 220687.4219
Epoch 100/150
188/188 [==============================] - 0s 2ms/step - loss: 75524120576.0000 - mse: 75524120576.0000 - mae: 220508.8125
Epoch 101/150
188/188 [==============================] - 0s 2ms/step - loss: 75580219392.0000 - mse: 75580219392.0000 - mae: 220622.9062
Epoch 102/150
188/188 [==============================] - 0s 2ms/step - loss: 75533565952.0000 - mse: 75533565952.0000 - mae: 220640.1406
Epoch 103/150
188/188 [==============================] - 0s 2ms/step - loss: 75536998400.0000 - mse: 75536998400.0000 - mae: 220584.6094
Epoch 104/150
188/188 [==============================] - 0s 2ms/step - loss: 75552382976.0000 - mse: 75552382976.0000 - mae: 220583.8125
Epoch 105/150
188/188 [==============================] - 1s 3ms/step - loss: 75511955456.0000 - mse: 75511955456.0000 - mae: 220587.5781
Epoch 106/150
188/188 [==============================] - 1s 3ms/step - loss: 75587493888.0000 - mse: 75587493888.0000 - mae: 220658.3750
Epoch 107/150
188/188 [==============================] - 1s 3ms/step - loss: 75546746880.0000 - mse: 75546746880.0000 - mae: 220594.8750
Epoch 108/150
188/188 [==============================] - 1s 3ms/step - loss: 75599601664.0000 - mse: 75599601664.0000 - mae: 220567.7969
Epoch 109/150
188/188 [==============================] - 1s 3ms/step - loss: 75490353152.0000 - mse: 75490353152.0000 - mae: 220473.6875
Epoch 110/150
188/188 [==============================] - 1s 3ms/step - loss: 75510636544.0000 - mse: 75510636544.0000 - mae: 220398.9688
Epoch 111/150
188/188 [==============================] - 1s 3ms/step - loss: 75552923648.0000 - mse: 75552923648.0000 - mae: 220638.5781
Epoch 112/150
188/188 [==============================] - 1s 3ms/step - loss: 75533737984.0000 - mse: 75533737984.0000 - mae: 220638.4844
Epoch 113/150
188/188 [==============================] - 1s 4ms/step - loss: 75562065920.0000 - mse: 75562057728.0000 - mae: 220627.0312
Epoch 114/150
188/188 [==============================] - 0s 3ms/step - loss: 75484119040.0000 - mse: 75484119040.0000 - mae: 220524.1250
Epoch 115/150
188/188 [==============================] - 0s 2ms/step - loss: 75510505472.0000 - mse: 75510505472.0000 - mae: 220578.1719
Epoch 116/150
188/188 [==============================] - 0s 2ms/step - loss: 75567521792.0000 - mse: 75567521792.0000 - mae: 220430.0156
Epoch 117/150
188/188 [==============================] - 0s 3ms/step - loss: 75563548672.0000 - mse: 75563548672.0000 - mae: 220665.9062
Epoch 118/150
188/188 [==============================] - 0s 3ms/step - loss: 75605975040.0000 - mse: 75605975040.0000 - mae: 220670.3438
Epoch 119/150
188/188 [==============================] - 1s 3ms/step - loss: 75545346048.0000 - mse: 75545346048.0000 - mae: 220629.2969
Epoch 120/150
188/188 [==============================] - 0s 2ms/step - loss: 75506819072.0000 - mse: 75506819072.0000 - mae: 220516.2969
Epoch 121/150
188/188 [==============================] - 0s 2ms/step - loss: 75621588992.0000 - mse: 75621588992.0000 - mae: 220654.3906
Epoch 122/150
188/188 [==============================] - 0s 3ms/step - loss: 75583414272.0000 - mse: 75583414272.0000 - mae: 220689.9219
Epoch 123/150
188/188 [==============================] - 1s 3ms/step - loss: 75493367808.0000 - mse: 75493367808.0000 - mae: 220428.0938
Epoch 124/150
188/188 [==============================] - 0s 3ms/step - loss: 75556200448.0000 - mse: 75556200448.0000 - mae: 220591.3750
Epoch 125/150
188/188 [==============================] - 0s 3ms/step - loss: 75572248576.0000 - mse: 75572248576.0000 - mae: 220690.6875
Epoch 126/150
188/188 [==============================] - 0s 2ms/step - loss: 75562835968.0000 - mse: 75562835968.0000 - mae: 220699.9531
Epoch 127/150
188/188 [==============================] - 0s 2ms/step - loss: 75530190848.0000 - mse: 75530190848.0000 - mae: 220550.8281
Epoch 128/150
188/188 [==============================] - 1s 3ms/step - loss: 75571994624.0000 - mse: 75571994624.0000 - mae: 220728.2188
Epoch 129/150
188/188 [==============================] - 0s 2ms/step - loss: 75576442880.0000 - mse: 75576442880.0000 - mae: 220660.6875
Epoch 130/150
188/188 [==============================] - 1s 3ms/step - loss: 75583135744.0000 - mse: 75583135744.0000 - mae: 220670.6406
Epoch 131/150
188/188 [==============================] - 1s 3ms/step - loss: 75502239744.0000 - mse: 75502239744.0000 - mae: 220481.2344
Epoch 132/150
188/188 [==============================] - 0s 3ms/step - loss: 75608489984.0000 - mse: 75608489984.0000 - mae: 221010.0469
Epoch 133/150
188/188 [==============================] - 0s 2ms/step - loss: 75572854784.0000 - mse: 75572854784.0000 - mae: 220645.3281
Epoch 134/150
188/188 [==============================] - 0s 3ms/step - loss: 75604271104.0000 - mse: 75604271104.0000 - mae: 220529.8906
Epoch 135/150
188/188 [==============================] - 1s 4ms/step - loss: 75471093760.0000 - mse: 75471093760.0000 - mae: 220421.6250
Epoch 136/150
188/188 [==============================] - 1s 3ms/step - loss: 75523039232.0000 - mse: 75523039232.0000 - mae: 220565.2656
Epoch 137/150
188/188 [==============================] - 1s 4ms/step - loss: 75476017152.0000 - mse: 75476017152.0000 - mae: 220466.2344
Epoch 138/150
188/188 [==============================] - 1s 4ms/step - loss: 75578531840.0000 - mse: 75578531840.0000 - mae: 220678.3594
Epoch 139/150
188/188 [==============================] - 1s 4ms/step - loss: 75506966528.0000 - mse: 75506966528.0000 - mae: 220604.7031
Epoch 140/150
188/188 [==============================] - 1s 4ms/step - loss: 75588403200.0000 - mse: 75588403200.0000 - mae: 220740.2656
Epoch 141/150
188/188 [==============================] - 1s 4ms/step - loss: 75604123648.0000 - mse: 75604123648.0000 - mae: 220729.2656
Epoch 142/150
188/188 [==============================] - 1s 3ms/step - loss: 75572879360.0000 - mse: 75572879360.0000 - mae: 220631.8750
Epoch 143/150
188/188 [==============================] - 0s 2ms/step - loss: 75495981056.0000 - mse: 75495981056.0000 - mae: 220578.8750
Epoch 144/150
188/188 [==============================] - 1s 3ms/step - loss: 75457421312.0000 - mse: 75457421312.0000 - mae: 220478.7344
Epoch 145/150
188/188 [==============================] - 0s 3ms/step - loss: 75670134784.0000 - mse: 75670134784.0000 - mae: 220716.0469
Epoch 146/150
188/188 [==============================] - 1s 3ms/step - loss: 75500183552.0000 - mse: 75500183552.0000 - mae: 220594.0625
Epoch 147/150

In [ ]:
xnew=np.array([[80000,8,6]])
ynew= model.predict(xnew)
print("X=%s, Predicted=%s" % (xnew[0], ynew[0]))

X=[80000     8     6], Predicted=[1442375.8]

In [ ]:
model.save('/content/test.h5')

In [ ]:
from tensorflow.python import keras
import tensorflow

modelnew = keras.models.load_model('/content/test.h5')
converter=tensorflow.lite.TFLiteConverter.from_keras_model(modelnew)
tflite_model = converter.convert()
open("car_model.tflite", "wb").write(tflite_model)

2552

In [ ]:
xnew=np.array([[70000,8,9]])
ynew= modelnew.predict(xnew)
print(type(ynew))
print("X=%s, Predicted=%s" % (xnew[0], int(ynew[0])))

<class 'numpy.ndarray'>
X=[70000     8     9], Predicted=1262541